version: '3.7'
services:
  db:
    image: postgres:16
    container_name: db_app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: -p 5433
    expose:
      - 5433
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: app
    command: >
      bash -c 
        "
          python manage.py makemigrations
          python manage.py migrate 
          python manage.py loaddata fixtures/users.json
          python manage.py loaddata fixtures/orders.json 
          python manage.py loaddata fixtures/items.json
          python manage.py runserver 0.0.0.0:8000
        "
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure:10
